package protocol;

public enum RequestType {
    UPLOAD_PROPERTIES_FILE,
    DELETE_COFFEE_SHOP,
    UPDATE_BASE_PRICE,
    GET_OPTION_SET_NAMES,
    GET_ALL_COFFEE_SHOP_NAMES,
    GET_COFFEE_SHOP,
    CLOSE_CONNECTION,
    DISCONNECT,
    ADD_OPTION_TO_OPTION_SET
}
