package protocol;

public enum RequestType {
    UPLOAD_PROPERTIES_FILE,
    SHOW_AVAILABLE_COFFEE_SHOPS,
    PRINT_COFFEE_SHOP,
    DELETE_COFFEE_SHOP,
    CONFIGURE_COFFEE_SHOP,
    UPDATE_BASE_PRICE,
    ADD_OPTION_TO_OPTION_SET
}
